

```yaml
---
# This config uses the HMC5883L, a triple-axis magnetometer, to read your water meter or gas meter.

substitutions:
  # water or gas
  device_class: 'water'

  # mdi:water or mdi:meter-gas
  device_icon: 'mdi:water'

  # For water one of: CCF, ft³, gal, L, m³
  # For gas one of: CCF, ft³, m³
  volume_unit: 'L'

  i2c_scl: GPIO5  # D1
  i2c_sda: GPIO4  # D2

  # Set these only if you have connected two QMC5883L to one device, see esphome-two-meters.yaml
  prefix_name: ''
  prefix_id: ''
  
  # Set device model (qmc5883l/hmc5883l) and address (0x1D/0x1E)
  magnetometer: hmc5883l
  magnetometer_address: '0x1E'

  hmc5883l_update_interval: '5ms'
  hmc5883l_oversampling: '4x'  # Korrigierter Wert

  volume_per_half_rotation_initial_value: '0.01008156'
  flow_update_interval_seconds: '10'

esphome:
  min_version: "2024.4.0" # This version includes https://github.com/esphome/esphome/pull/6456
  # Default loop interval is 16ms. Setting it to 0 to make updates faster.
  # Without setting this, the actual update interval of qmc5883l is: 6ms on ESP32, 10ms on ESP8266.
  # With this, it's 5ms on ESP32, 8ms on ESP8266.
  on_boot:
    then:
      - lambda: App.set_loop_interval(0);

logger:
  logs:
    qmc5883l: INFO

api:
  services:
    # Based on https://esphome.io/components/sensor/pulse_meter.html#re-setting-the-total-pulse-count
    # Useful if you would like the total sensor to match what you see on your meter you are trying to match.
    - service: ${prefix_id}set_total
      variables:
        new_total: float
      then:
        - globals.set:
            id: ${prefix_id}half_rotations_total
            value: !lambda 'return new_total / id(${prefix_id}volume_per_half_rotation).state;'

globals:
  - id: ${prefix_id}half_rotations_total
    type: long
    restore_value: yes
    initial_value: '0'
  - id: ${prefix_id}half_rotations_flow
    type: long
    restore_value: no
    initial_value: '0'
  - id: ${prefix_id}axis_value_high
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: ${prefix_id}calibrating
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: ${prefix_id}calibrating_axis_x_min
    type: float
    restore_value: no
  - id: ${prefix_id}calibrating_axis_x_max
    type: float
    restore_value: no
  - id: ${prefix_id}calibrating_axis_y_min
    type: float
    restore_value: no
  - id: ${prefix_id}calibrating_axis_y_max
    type: float
    restore_value: no
  - id: ${prefix_id}calibrating_axis_z_min
    type: float
    restore_value: no
  - id: ${prefix_id}calibrating_axis_z_max
    type: float
    restore_value: no

number:
  - platform: template
    id: ${prefix_id}volume_per_half_rotation
    name: ${prefix_name}Volume per half rotation
    entity_category: config
    mode: box
    min_value: 0
    max_value: 9999999
    step: 0.000000001
    initial_value: ${volume_per_half_rotation_initial_value}
    update_interval: never
    restore_value: true
    optimistic: true
    unit_of_measurement: ${volume_unit}

  - platform: template
    id: ${prefix_id}threshold_lower
    name: ${prefix_name}Threshold lower
    entity_category: config
    mode: box
    min_value: -9999
    max_value: 9999
    step: 0.1
    initial_value: -9999
    update_interval: never
    restore_value: true
    optimistic: true
    unit_of_measurement: µT

  - platform: template
    id: ${prefix_id}threshold_upper
    name: ${prefix_name}Threshold upper
    entity_category: config
    mode: box
    min_value: -9999
    max_value: 9999
    step: 0.1
    initial_value: 9999
    update_interval: never
    restore_value: true
    optimistic: true
    unit_of_measurement: µT

  - platform: template
    id: ${prefix_id}calibration_seconds
    name: ${prefix_name}Calibration time
    entity_category: config
    icon: mdi:timer
    mode: box
    min_value: 1
    max_value: 999
    step: 1
    initial_value: 5
    update_interval: never
    restore_value: true
    optimistic: true
    unit_of_measurement: s

select:
  - platform: template
    id: ${prefix_id}axis
    name: ${prefix_name}Axis
    entity_category: config
    options:
      - x
      - y
      - z
      - None
    initial_option: None
    update_interval: never
    restore_value: true
    optimistic: true

button:
  - platform: template
    id: ${prefix_id}calibrate_button
    name: ${prefix_name}Calibrate axis
    entity_category: config
    on_press:
      - lambda: |-
          ESP_LOGI("calibration", "Starting calibration. Make sure ${device_class} is running");
          id(${prefix_id}calibrating_axis_x_min) = std::numeric_limits<float>::max();
          id(${prefix_id}calibrating_axis_x_max) = std::numeric_limits<float>::lowest();
          id(${prefix_id}calibrating_axis_y_min) = std::numeric_limits<float>::max();
          id(${prefix_id}calibrating_axis_y_max) = std::numeric_limits<float>::lowest();
          id(${prefix_id}calibrating_axis_z_min) = std::numeric_limits<float>::max();
          id(${prefix_id}calibrating_axis_z_max) = std::numeric_limits<float>::lowest();
          id(${prefix_id}calibrating) = true;
      - delay: !lambda return id(${prefix_id}calibration_seconds).state * 1000;
      - lambda: |-
          id(${prefix_id}calibrating) = false;
          float x_range = id(${prefix_id}calibrating_axis_x_max) - id(${prefix_id}calibrating_axis_x_min);
          float y_range = id(${prefix_id}calibrating_axis_y_max) - id(${prefix_id}calibrating_axis_y_min);
          float z_range = id(${prefix_id}calibrating_axis_z_max) - id(${prefix_id}calibrating_axis_z_min);
          if (x_range < 0) {
            ESP_LOGW("${prefix_id}calibration", "Didn't get any values for x");
          } else {
            ESP_LOGI("${prefix_id}calibration", "x ranged from %.2f to %.2f",
                     id(${prefix_id}calibrating_axis_x_min), id(${prefix_id}calibrating_axis_x_max));
          }
          if (y_range < 0) {
            ESP_LOGW("${prefix_id}calibration", "Didn't get any values for y");
          } else {
            ESP_LOGI("${prefix_id}calibration", "y ranged from %.2f to %.2f",
                     id(${prefix_id}calibrating_axis_y_min), id(${prefix_id}calibrating_axis_y_max));
          }
          if (z_range < 0) {
            ESP_LOGW("${prefix_id}calibration", "Didn't get any values for z");
          } else {
            ESP_LOGI("${prefix_id}calibration", "z ranged from %.2f to %.2f",
                     id(${prefix_id}calibrating_axis_z_min), id(${prefix_id}calibrating_axis
